Models/Asset.cs
using System.ComponentModel.DataAnnotations;

namespace Edison.Models
{
    public class Asset
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string? AssetCode { get; set; }

        [Required]
        public string? AssetName { get; set; }

        public int AssetCategoryID { get; set; }
        public AssetCategory? AssetCategory { get; set; }

        public int DepartmentID { get; set; }
        public Department? Department { get; set; }

        [Required]
        public DateTime PurchaseDate { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public string? SupplierName { get; set; }
    }
}

Controllers/AssetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Edison.Data;
using Edison.Models;

namespace Edison.Controllers
{
    [Authorize]
    public class AssetController : Controller
    {
        private readonly ILogger<AssetController> _logger;

        public AssetController(ILogger<AssetController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<Models.Asset> assets = new List<Models.Asset>();

            try
            {
                using (var context = new EdisonContext())
                {
                    assets = (from c in context.Asset
                              select new Asset
                              {
                                  ID = c.ID,
                                  AssetCode = c.AssetCode,
                                  AssetName = c.AssetName,
                                  AssetCategory = context.AssetCategory.Where(x => x.ID.Equals(c.AssetCategoryID)).First(),
                                  Department = context.Department.Where(x => x.ID.Equals(c.DepartmentID)).First(),
                                  PurchaseDate = c.PurchaseDate,
                                  Price = c.Price,
                                  SupplierName = c.SupplierName
                              }).ToList();
                }
            }
            catch
            {
                _logger.Log(LogLevel.Error, "Load Error", assets);
                return RedirectToAction("Error", "Home");
            }

            _logger.Log(LogLevel.Information, "Load Success", assets);
            return View(assets);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Models.AssetModel model = new Models.AssetModel();
            using (var context = new EdisonContext())
            {
                model.AssetCategories = context.AssetCategory.ToList();
                model.Departments = context.Department.ToList();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Models.AssetModel model)
        {
            try
            {
                using (var context = new EdisonContext())
                {
                    context.Asset.Add(model.Asset!);
                    context.Entry(model.Asset!).State = EntityState.Added;
                    context.Entry(model.Asset!.AssetCategory!).State = EntityState.Unchanged;
                    context.Entry(model.Asset!.Department!).State = EntityState.Unchanged;

                    context.SaveChanges();
                }
            }
            catch
            {
                _logger.Log(LogLevel.Error, "Create Error", model.Asset);
                return RedirectToAction("Error", "Home");
            }

            _logger.Log(LogLevel.Information, "Create Success", model.Asset);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Models.AssetModel model = new Models.AssetModel();

            try
            {
                using (var context = new EdisonContext())
                {
                    model.Asset = context.Asset.First(a => a.ID.Equals(Id));
                    model.AssetCategories = context.AssetCategory.ToList();
                    model.Departments = context.Department.ToList();
                }
            }
            catch
            {
                _logger.Log(LogLevel.Error, "Load Edit Error", Id);
                return RedirectToAction("Error", "Home");
            }

            _logger.Log(LogLevel.Information, "Load Edit Success", model.Asset);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Models.AssetModel model)
        {
            using (var context = new EdisonContext())
            {
                try
                {
                    context.Asset.Update(model.Asset!);
                    context.Entry(model.Asset!).State = EntityState.Modified;
                    context.Entry(model.Asset!.AssetCategory!).State = EntityState.Unchanged;
                    context.Entry(model.Asset!.Department!).State = EntityState.Unchanged;
                    context.SaveChanges();
                }
                catch
                {
                    model.AssetCategories = context.AssetCategory.ToList();
                    model.Departments = context.Department.ToList();

                    _logger.Log(LogLevel.Error, "Edit Error", model.Asset);
                    return View(model);
                }
            }

            _logger.Log(LogLevel.Information, "Edit Success", model.Asset);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            try
            {
                using (var context = new EdisonContext())
                {
                    var asset = context.Asset.First(a => a.ID.Equals(Id));
                    context.Asset.Remove(asset);
                    context.Entry(asset).State = EntityState.Deleted;
                    context.SaveChanges();
                }
            }
            catch
            {
                _logger.Log(LogLevel.Error, "Delete Error", Id);
                return RedirectToAction("Error", "Home");
            }

            _logger.Log(LogLevel.Information, "Delete Success", Id);
            return RedirectToAction("Index");
        }
    }
}

Views/Asset/Create.cshtml
@model Edison.Models.AssetModel

<h1>Create Asset</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Asset!.AssetCode" class="control-label"></label>
                <input asp-for="Asset!.AssetCode" class="form-control" />
                <span asp-validation-for="Asset!.AssetCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.AssetName" class="control-label"></label>
                <input asp-for="Asset!.AssetName" class="form-control" />
                <span asp-validation-for="Asset!.AssetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.AssetCategory" class="control-label"></label>
                <select asp-for="Asset!.AssetCategory!.ID" asp-items="@(new SelectList(Model.AssetCategories, "ID", "Name"))" class="form-control"></select>
                <span asp-validation-for="Asset!.AssetCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.Department" class="control-label"></label>
                <select asp-for="Asset!.Department!.ID" asp-items="@(new SelectList(Model.Departments, "ID", "Name"))" class="form-control"></select>
                <span asp-validation-for="Asset!.Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.PurchaseDate" class="control-label"></label>
                <input asp-for="Asset!.PurchaseDate" class="form-control" value="" type="datetime"/>
                <span asp-validation-for="Asset!.PurchaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.Price" class="control-label"></label>
                <input asp-for="Asset!.Price" class="form-control" type="number" />
                <span asp-validation-for="Asset!.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.SupplierName" class="control-label"></label>
                <input asp-for="Asset!.SupplierName" class="form-control" />
                <span asp-validation-for="Asset!.SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Asset/Edit.cshtml
@model Edison.Models.AssetModel

<h1>Edit Asset</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Asset!.ID" />
            <div class="form-group">
                <label asp-for="Asset!.AssetCode" class="control-label"></label>
                <input asp-for="Asset!.AssetCode" class="form-control" />
                <span asp-validation-for="Asset!.AssetCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.AssetName" class="control-label"></label>
                <input asp-for="Asset!.AssetName" class="form-control" />
                <span asp-validation-for="Asset!.AssetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.AssetCategory" class="control-label"></label>
                <select asp-for="Asset!.AssetCategory!.ID" asp-items="@(new SelectList(Model.AssetCategories, "ID", "Name"))" class="form-control"></select>
                <span asp-validation-for="Asset!.AssetCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.Department" class="control-label"></label>
                <select asp-for="Asset!.Department!.ID" asp-items="@(new SelectList(Model.Departments, "ID", "Name"))" class="form-control"></select>
                <span asp-validation-for="Asset!.Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.PurchaseDate" class="control-label"></label>
                <input asp-for="Asset!.PurchaseDate" class="form-control" value="" type="datetime" />
                <span asp-validation-for="Asset!.PurchaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.Price" class="control-label"></label>
                <input asp-for="Asset!.Price" class="form-control" type="number" />
                <span asp-validation-for="Asset!.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asset!.SupplierName" class="control-label"></label>
                <input asp-for="Asset!.SupplierName" class="form-control" />
                <span asp-validation-for="Asset!.SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Asset/Index.cshtml
@model List<Edison.Models.Asset>

@Html.ActionLink("Create New", "Create", "Asset")
<br />
<br />
<div class="text-center">
    <table id="table-tasks" class="display">
        <thead>
            <tr>
                <th>Asset Code</th>
                <th>Asset Name</th>
                <th>Asset Category</th>
                <th>Department</th>
                <th>Purchase Date</th>
                <th>Price</th>
                <th>Supplier Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssetCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssetName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssetCategory!.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department!.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PurchaseDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SupplierName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.ID }, new { onclick = "return confirm('Are you sure you wish to delete this task?');" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table-tasks').DataTable();
        });
    </script>
}